# -*- coding: utf-8 -*-
"""Energy Demand Forecasting (LSTM) — 24 Hours

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/umargoro/energy-demand-forecasting-lstm-24-hours.ee7ce272-5e5c-45ec-8334-5ecf5e8dd52b.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260604/auto/storage/goog4_request%26X-Goog-Date%3D20260604T214336Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D12da79192b417fc2cbfc6b742ad6ad5d44144c694b4c1ce452ce4fcc5456dab8bbe3472c1aa74bf92df50ecaff7a44bc40c4421e8e67bbccecca292050773b0bbfde6c89210afdfc17ed902978ff3088ed2a3f6d00268048c2f65f2313d27613421713a63ccd2ef6b0edcc2f0e70a66f0088a9061df0017bc54b9a4fe859d46234f76c0711f7b3c7b7d5973ead2c786e667f037b6329e2e599b538fddf2328605e56c800b577f4bf9107e1ea4d731a42d0dcb7af8815e0b4cdcb8fb1a3ba3499c0daec00771a1c07ff5c8552be360db815570e190e65e85e7a50853c4ae539291f1849e3bb41009eba014f2c5f042ee6c20a33ae1ac1f3be7282a8290cc5e48d
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
robikscube_hourly_energy_consumption_path = kagglehub.dataset_download('robikscube/hourly-energy-consumption')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

df=pd.read_csv( "/kaggle/input/datasets/robikscube/hourly-energy-consumption/PJME_hourly.csv")
#setting the datetime column as the index
df=df.set_index("Datetime")
#casting the date column from object to datetime
df.index=pd.to_datetime(df.index)

#Visualizing the data

df.plot(style="-", figsize=(15, 5), color="b", title="Energy Consumed In MegaWatt")
plt.savefig("prediction_Plot.png", dpi=300, bbox_inches="tight")
plt.show()

df.head(5)

data=df[["PJME_MW"]].values
data.shape

#Data Normalization
scaler = MinMaxScaler(feature_range=(0, 1))
data_scaled = scaler.fit_transform(data)
data_scaled

#Create sequences (time-series windowing)
def create_dataset(data, time_step=24):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:i+time_step])
        y.append(data[i+time_step])
    return np.array(X), np.array(y)

time_step = 24
X, y = create_dataset(data_scaled, time_step)

X = X.reshape(X.shape[0], X.shape[1], 1)

#Splitting the data into train and testing split
train_size = int(len(X) * 0.8)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

X_test.shape

#Building the Model
model = Sequential()

model.add(LSTM(64, return_sequences=True, input_shape=(time_step, 1)))
model.add(LSTM(32))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')
model.summary()

#Training the model
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

#Predictions
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

train_pred = scaler.inverse_transform(train_pred)
test_pred = scaler.inverse_transform(test_pred)

y_train_inv = scaler.inverse_transform(y_train)
y_test_inv = scaler.inverse_transform(y_test)

#Evaluation metrics
mae = mean_absolute_error(y_test_inv, test_pred)
rmse = np.sqrt(mean_squared_error(y_test_inv, test_pred))
mape = np.mean(np.abs((y_test_inv - test_pred) / y_test_inv)) * 100

print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)

#Plot results
plt.figure(figsize=(10,5))
plt.plot(y_test_inv, label="Actual")
plt.plot(test_pred, label="Predicted")
plt.legend()
plt.title("Energy Demand Forecasting (LSTM)")
plt.savefig("prediction_Plot.png", dpi=300, bbox_inches="tight")
plt.show()

#Actual versus Predicted plot
plt.plot(y_test_inv, label="Actual")
plt.plot(test_pred, label="predicted")
plt.title("Actual versus Predicted Energy Demand")
plt.ylabel("Demand")
plt.legend()
plt.savefig("prediction_Plot.png", dpi=300, bbox_inches="tight")
plt.show()

#Correlation plot
plt.figure(figsize=(6,6))

plt.scatter(y_test_inv, test_pred, alpha=0.5)

plt.xlabel('Actual Demand')
plt.ylabel('Predicted Demand')
plt.title('Actual vs Predicted Scatter Plot')
plt.savefig("prediction_Plot.png", dpi=300, bbox_inches="tight")
plt.show()

#Saving the model
model.save("LSTM_ENERFY_FORECSTING_MODEL.keras")

from tensorflow.keras.models import load_model

model_loaded = load_model("LSTM_ENERFY_FORECSTING_MODEL.keras")

model_loaded.summary()

import os


print(os.listdir())

